version: '3.3'

services:
  remotely-prod:
    image: translucency/remotely:latest
    #command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data/remotely-data:/remotely-data
    # ATENÇÂO - NÂO ESQUEÇA ALTERAR O NOME DO SERVIÇO NAS ROTAS SENÃO QUEBRA AS OUTRAS APLICAÇÕES 
    # (ex: troque traefik.http.routers.PORTAINER..... por um nome representativo e único da sua aplicação  ) 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remotely-prod.rule=Host(`remoto.<YOUR_DOMAIN>`)"
      - "traefik.http.services.remotely-prod.loadbalancer.server.port=5000"
      - "traefik.http.routers.remotely-prod.entrypoints=websecure"
      - "traefik.http.routers.remotely-prod.tls"
    networks:
      - proxy

networks:
  proxy:
     external: true

